.PHONY: vim templates
FILES = fantasyStocks/settings.py fantasyStocks/urls.py stocks/admin.py stocks/models.py stocks/tests.py stocks/views.py stocks/stockurls.py

vim : 
	vim $(FILES)
templates : 
	vim stocks/templates/*
