# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-01 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksApi', '0002_androidtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidtoken',
            name='token',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
