# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 00:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_auto_20151222_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 30, 0, 17, 19, 730522, tzinfo=utc)),
        ),
    ]
