# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 22:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_auto_20151229_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='name',
            field=models.CharField(max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 3, 22, 4, 32, 985134, tzinfo=utc)),
        ),
    ]
