# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-05 23:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0018_auto_20160228_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 5, 22, 48, 19, 760661, tzinfo=utc)),
        ),
    ]
