# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-12 22:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0019_auto_20170405_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 12, 21, 48, 16, 136171, tzinfo=utc)),
        ),
    ]
