# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-01 21:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0020_auto_20170412_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 1, 21, 13, 30, 805738, tzinfo=utc)),
        ),
    ]
